[workspace]
authors = ["Kevin Abraham <abraha2d@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "ha_kasa_helper"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"

[pypi-dependencies]
python-kasa = ">=0.10.2, <0.11"
homeassistant = ">=2025.4.4, <2025.5"
pyright = ">=1.1.400, <1.2"
ruff = ">=0.11.8, <0.12"
